### PR TITLE
Fixing regressions introduced with PR #63

### LINKED ISSUE #64: PR #63 introduced two regressions
@DaniRey your PR #63 introduced two regressions:
- sbt is no longer "prepared", it needs to download itself on startup
- scala is no longer on the path

I think this is due to still using the directory `root` in some places, e.g. in 
`echo "export PATH=~/scala-$SCALA_VERSION/bin:$PATH" >> /root/.bashrc`.

Could you please take a look and fix that?

### PR DESCRIPTION
**Pull request by DaniRey**
- reorganize Dockerfile
 - download and install sbt as root
 - create and switch to sbtuser
 - download and provide Scala
 - prepare sbt
 - fixes #64

### CODE REVIEW

**Comment by hseeberger** [comment]
Thanks!

**Comment by DaniRey** [comment]
@hseeberger Thank you for the quick merge! Would you mind adding a comment here as soon as it is released to Docker Hub?

**Comment by hseeberger** [comment]
8u212_2.12.8_1.2.8 should be on its way.

**Comment by DaniRey** [comment]
Thank you. I'll wait for 11.0.2_2.12.8_1.2.8. Till then I have your Dockerfile at the beginning of mine https://github.com/unic/ScalaWebTest/tree/master/docker/scalawebtest-sbt :-D

**Pull request merged**
