### PR TITLE
add hooks to build multiple image

### LINKED ISSUE #71: Build for multiple Java base images
There are a lot of PRs upgrading (e.g. to Java 12) or even downgrading (back to Java 8) the Java version. There's also the wish for using a slim variant of the Java base image.

Therefore I'd like to enable the build to support multiple Java base images. Yet I do not know how to achieve that and I'm looking for help.

### PR DESCRIPTION
**Pull request by Ksisu**
resolve #71
- add build arguments to Dockerfile
  - `BASE_IMAGE_TAG` - openjdk image tag (for base image)
  - `SBT_VERSION`
  - `SCALA_VERSION`
- create a new Dockerfile for openjdk12 (because it is not debian based image)
- create `debian` folder for the original Dockerfile and `oracle` for the new one
- add dockerhub hooks for building multiple image
  - `build.sh` - build an image. Use environment variables:
    - `TAG` - the new image's tag `hseeberger/scala-sbt:${TAG}`
    - `DOCKER_CONTEXT` - set context in docker build command (eg `debian` / `oracle`)
    - `BASE_IMAGE_TAG`, `SBT_VERSION`, `SCALA_VERSION` - docker build arguments
  - `vars.sh` - create an environment variable that contains the multiple image build params in lines
    - one line one build
    - every line set the environment variables that used in `build.sh` (`TAG`, `DOCKER_CONTEXT`,  `BASE_IMAGE_TAG`, `SBT_VERSION`, `SCALA_VERSION`)
  - `build` - dockerhub build hook file. Read the `vars.sh` and call the `build.sh` for each line
  - `push` - dockerhub push hook file. Check it is the `master` branch. Push all created image.

The dockerhub hook files override the automated build parameters. So in the dockerhub you only need one automatic build trigger, for the master with the default params:
screenshot_2019-07-03_08-12-52

It is very slow because one "dockerhub build" build the all images. The current version was 40 minutes. But it works:
screenshot_2019-07-03_08-17-15

ps.:  sometimes the build failed because the sbt/scala download failed.

### CODE REVIEW

**Comment by hseeberger** [comment]
Looks really awesome. Thanks a lot!
I do not know enough to review this, but hey, let's give it a try.

**Comment by igstan** [comment]
Folks, why was it necessary to include the Scala and sbt versions in the image tags? These versions are usually not that important, because the developer can set them via `build.sbt` and `project/build.properties` respectively.

**Comment by hseeberger** [comment]
@igstan what would you suggest to distinguish the different images, e.g. images with different versions of sbt?

**Comment by igstan** [comment]
@hseeberger I think what I'm proposing (I can attempt a PR if we agree on anything) is to publish tags _without_ an sbt or Scala version. These can be the latest and greatest, because I can override them in `build.sbt` (for Scala version) and `project/build.properties` (for sbt version). This is unless I'm missing some knowledge about how sbt works.

For example: `hseeberger/scala-sbt:8u222` would be enough, because I care about the JVM version, but not about the other versions.

**Comment by hseeberger** [comment]
Thanks for the explanation.

I agree that assumably most users will only use this image for building in a Docker environment, i.e. in a setting where they do not use the Scala installation and normally do not care about the sbt launcher. Yet sbt potentially does differ from version to version in the launcher (old launchers potentially cannot launch recent sbt versions). And of course the Scala installation does differ in each version. Hence these versions do make a difference.

Do the versions hurt? If you do not care about them, why not just use some version with a 1.2.x sbt version which should be fine for quite some time?

**Comment by igstan** [comment]
Thanks. They don't hurt, that's true. My opening of this issue was triggered by the fact that I have a Docker file using `8u181_2.12.8_1.2.8`, but my project uses Scala 2.12.9 instead of 2.12.8 and I got a bit confused — my thinking was "Should I care about that?" Which is why I asked why it was necessary to add those versions.

**Pull request merged**
