### PR TITLE
scala 3.0.0-RC2

### PR DESCRIPTION
**Pull request by francisdb**

### CODE REVIEW

**Comment by hseeberger** [comment]
Nice! I missed the release of Scala 3 RC1.

**Comment by francisdb** [comment]
@hseeberger I just asked @SethTisue if the files will be available on the usual download location

**Comment by francisdb** [comment]
see also https://users.scala-lang.org/t/downloading-scala-3/7136/3 so might try to get it from there

**Comment by francisdb** [comment]
Looks like we will also need to wait for sbt 1.5.x
https://github.com/sbt/sbt/releases/tag/v1.5.0-M2

**Comment by SethTisue** [comment]
> @hseeberger I just asked @SethTisue if the files will be available on the usual download location

I doubt it, I think you'll need to keep the "if Scala 2 this, if Scala 3 that" logic

**Comment by francisdb** [comment]
Thanks for the update @SethTisue

**Pull request merged**
